//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CordenadasCab24
    {
        public int IdCordenadaCab24 { get; set; }
        public int IdFolio { get; set; }
        public int Consecutivo { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public long IdSesion { get; set; }
    }
}
