//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnercableConexion : DbContext
    {
        public EnercableConexion()
            : base("name=EnercableConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacoras> Bitacoras { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<PermisosPerfiles> PermisosPerfiles { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Cabeceras> Cabeceras { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<CargosPersonas> CargosPersonas { get; set; }
        public virtual DbSet<CordenadasCab24> CordenadasCab24 { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<TrabajosRealizados> TrabajosRealizados { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<vwUsuarios> vwUsuarios { get; set; }
        public virtual DbSet<vwServicios> vwServicios { get; set; }
        public virtual DbSet<vwPersonas> vwPersonas { get; set; }
        public virtual DbSet<vwProveedores> vwProveedores { get; set; }
        public virtual DbSet<vwUnidades> vwUnidades { get; set; }
        public virtual DbSet<vwCargos> vwCargos { get; set; }
        public virtual DbSet<vwPerfiles> vwPerfiles { get; set; }
        public virtual DbSet<Folios> Folios { get; set; }
        public virtual DbSet<Archivos> Archivos { get; set; }
        public virtual DbSet<Carpetas> Carpetas { get; set; }
        public virtual DbSet<ClasificacionServicios> ClasificacionServicios { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<TipoArchivo> TipoArchivo { get; set; }
        public virtual DbSet<vwClasificacionServicios> vwClasificacionServicios { get; set; }
        public virtual DbSet<vwDepartamentos> vwDepartamentos { get; set; }
        public virtual DbSet<vwTrabajosRealizados> vwTrabajosRealizados { get; set; }
        public virtual DbSet<vwFolios> vwFolios { get; set; }
        public virtual DbSet<vwArchivos> vwArchivos { get; set; }
        public virtual DbSet<Formatos> Formatos { get; set; }
        public virtual DbSet<ServiciosPorFormato> ServiciosPorFormato { get; set; }
        public virtual DbSet<vwFormatos> vwFormatos { get; set; }
    
        public virtual int GuardarBitacora(string accion, Nullable<long> idSesion)
        {
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarBitacora", accionParameter, idSesionParameter);
        }
    
        public virtual ObjectResult<CrearSesion_Result> CrearSesion(string usuario, string contraseña, string ip)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var ipParameter = ip != null ?
                new ObjectParameter("Ip", ip) :
                new ObjectParameter("Ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CrearSesion_Result>("CrearSesion", usuarioParameter, contraseñaParameter, ipParameter);
        }
    
        public virtual int EliminarPermisoPerfil(Nullable<int> idPermisoPerfil, Nullable<long> idSesion)
        {
            var idPermisoPerfilParameter = idPermisoPerfil.HasValue ?
                new ObjectParameter("IdPermisoPerfil", idPermisoPerfil) :
                new ObjectParameter("IdPermisoPerfil", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPermisoPerfil", idPermisoPerfilParameter, idSesionParameter);
        }
    
        public virtual int GuardarPerfil(Nullable<int> idPerfil, Nullable<int> idEstatus, string perfil, Nullable<long> idSesion)
        {
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("IdPerfil", idPerfil) :
                new ObjectParameter("IdPerfil", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var perfilParameter = perfil != null ?
                new ObjectParameter("Perfil", perfil) :
                new ObjectParameter("Perfil", typeof(string));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarPerfil", idPerfilParameter, idEstatusParameter, perfilParameter, idSesionParameter);
        }
    
        public virtual int GuardarPermisoPerfil(Nullable<int> idModulo, Nullable<int> idPerfil, Nullable<long> idSesion)
        {
            var idModuloParameter = idModulo.HasValue ?
                new ObjectParameter("IdModulo", idModulo) :
                new ObjectParameter("IdModulo", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("IdPerfil", idPerfil) :
                new ObjectParameter("IdPerfil", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarPermisoPerfil", idModuloParameter, idPerfilParameter, idSesionParameter);
        }
    
        public virtual int GuardarUsuario(Nullable<int> idUsuario, string usuario, string password, Nullable<int> idPerfil, string nombre, string paterno, string materno, string correo, string telefono, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("IdPerfil", idPerfil) :
                new ObjectParameter("IdPerfil", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarUsuario", idUsuarioParameter, usuarioParameter, passwordParameter, idPerfilParameter, nombreParameter, paternoParameter, maternoParameter, correoParameter, telefonoParameter, idEstatusParameter, idSesionParameter);
        }
    
        [DbFunction("EnercableConexion", "DividirCadena")]
        public virtual IQueryable<string> DividirCadena(string cadena, string divisor)
        {
            var cadenaParameter = cadena != null ?
                new ObjectParameter("Cadena", cadena) :
                new ObjectParameter("Cadena", typeof(string));
    
            var divisorParameter = divisor != null ?
                new ObjectParameter("Divisor", divisor) :
                new ObjectParameter("Divisor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[EnercableConexion].[DividirCadena](@Cadena, @Divisor)", cadenaParameter, divisorParameter);
        }
    
        public virtual int GuardarFolio(Nullable<int> idFolio, string folio, string ciudad, string estado, string cluster, string oLT, string clientesAfectados, string fallaReportada, string fechaYHoraDeAsignacionDespacho, string fechaYHoraDeAsignacionProvista, string horaDeLlegadaALaZona, string horaDeLaPrimeraMedicion, string ubicacionDePrimerSegundoNivelYDerivacionConSusFibras, string causaDelDano, string ubicacionDelDano, string coordenadasDelDanoX, string coordenadasDelDanoY, string descripcionDeActividades, string potencialInicia, string potencialFinal, string fechaHoraFinalReparacion, Nullable<int> idPersona_TecnicoAtiende, Nullable<int> idProveedor, Nullable<int> idPersona_Supervisor, Nullable<int> idPersona_AtendioDespacho, string justificacionDeSLA, Nullable<bool> actualizarTrabajosRealizados, string trabajosRealizados, Nullable<bool> actualizarCordenadasCab24, string cordenadasCab24, Nullable<long> idSesion, Nullable<int> idFormato)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("Ciudad", ciudad) :
                new ObjectParameter("Ciudad", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var clusterParameter = cluster != null ?
                new ObjectParameter("Cluster", cluster) :
                new ObjectParameter("Cluster", typeof(string));
    
            var oLTParameter = oLT != null ?
                new ObjectParameter("OLT", oLT) :
                new ObjectParameter("OLT", typeof(string));
    
            var clientesAfectadosParameter = clientesAfectados != null ?
                new ObjectParameter("ClientesAfectados", clientesAfectados) :
                new ObjectParameter("ClientesAfectados", typeof(string));
    
            var fallaReportadaParameter = fallaReportada != null ?
                new ObjectParameter("FallaReportada", fallaReportada) :
                new ObjectParameter("FallaReportada", typeof(string));
    
            var fechaYHoraDeAsignacionDespachoParameter = fechaYHoraDeAsignacionDespacho != null ?
                new ObjectParameter("FechaYHoraDeAsignacionDespacho", fechaYHoraDeAsignacionDespacho) :
                new ObjectParameter("FechaYHoraDeAsignacionDespacho", typeof(string));
    
            var fechaYHoraDeAsignacionProvistaParameter = fechaYHoraDeAsignacionProvista != null ?
                new ObjectParameter("FechaYHoraDeAsignacionProvista", fechaYHoraDeAsignacionProvista) :
                new ObjectParameter("FechaYHoraDeAsignacionProvista", typeof(string));
    
            var horaDeLlegadaALaZonaParameter = horaDeLlegadaALaZona != null ?
                new ObjectParameter("HoraDeLlegadaALaZona", horaDeLlegadaALaZona) :
                new ObjectParameter("HoraDeLlegadaALaZona", typeof(string));
    
            var horaDeLaPrimeraMedicionParameter = horaDeLaPrimeraMedicion != null ?
                new ObjectParameter("HoraDeLaPrimeraMedicion", horaDeLaPrimeraMedicion) :
                new ObjectParameter("HoraDeLaPrimeraMedicion", typeof(string));
    
            var ubicacionDePrimerSegundoNivelYDerivacionConSusFibrasParameter = ubicacionDePrimerSegundoNivelYDerivacionConSusFibras != null ?
                new ObjectParameter("UbicacionDePrimerSegundoNivelYDerivacionConSusFibras", ubicacionDePrimerSegundoNivelYDerivacionConSusFibras) :
                new ObjectParameter("UbicacionDePrimerSegundoNivelYDerivacionConSusFibras", typeof(string));
    
            var causaDelDanoParameter = causaDelDano != null ?
                new ObjectParameter("CausaDelDano", causaDelDano) :
                new ObjectParameter("CausaDelDano", typeof(string));
    
            var ubicacionDelDanoParameter = ubicacionDelDano != null ?
                new ObjectParameter("UbicacionDelDano", ubicacionDelDano) :
                new ObjectParameter("UbicacionDelDano", typeof(string));
    
            var coordenadasDelDanoXParameter = coordenadasDelDanoX != null ?
                new ObjectParameter("CoordenadasDelDanoX", coordenadasDelDanoX) :
                new ObjectParameter("CoordenadasDelDanoX", typeof(string));
    
            var coordenadasDelDanoYParameter = coordenadasDelDanoY != null ?
                new ObjectParameter("CoordenadasDelDanoY", coordenadasDelDanoY) :
                new ObjectParameter("CoordenadasDelDanoY", typeof(string));
    
            var descripcionDeActividadesParameter = descripcionDeActividades != null ?
                new ObjectParameter("DescripcionDeActividades", descripcionDeActividades) :
                new ObjectParameter("DescripcionDeActividades", typeof(string));
    
            var potencialIniciaParameter = potencialInicia != null ?
                new ObjectParameter("PotencialInicia", potencialInicia) :
                new ObjectParameter("PotencialInicia", typeof(string));
    
            var potencialFinalParameter = potencialFinal != null ?
                new ObjectParameter("PotencialFinal", potencialFinal) :
                new ObjectParameter("PotencialFinal", typeof(string));
    
            var fechaHoraFinalReparacionParameter = fechaHoraFinalReparacion != null ?
                new ObjectParameter("FechaHoraFinalReparacion", fechaHoraFinalReparacion) :
                new ObjectParameter("FechaHoraFinalReparacion", typeof(string));
    
            var idPersona_TecnicoAtiendeParameter = idPersona_TecnicoAtiende.HasValue ?
                new ObjectParameter("IdPersona_TecnicoAtiende", idPersona_TecnicoAtiende) :
                new ObjectParameter("IdPersona_TecnicoAtiende", typeof(int));
    
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            var idPersona_SupervisorParameter = idPersona_Supervisor.HasValue ?
                new ObjectParameter("IdPersona_Supervisor", idPersona_Supervisor) :
                new ObjectParameter("IdPersona_Supervisor", typeof(int));
    
            var idPersona_AtendioDespachoParameter = idPersona_AtendioDespacho.HasValue ?
                new ObjectParameter("IdPersona_AtendioDespacho", idPersona_AtendioDespacho) :
                new ObjectParameter("IdPersona_AtendioDespacho", typeof(int));
    
            var justificacionDeSLAParameter = justificacionDeSLA != null ?
                new ObjectParameter("JustificacionDeSLA", justificacionDeSLA) :
                new ObjectParameter("JustificacionDeSLA", typeof(string));
    
            var actualizarTrabajosRealizadosParameter = actualizarTrabajosRealizados.HasValue ?
                new ObjectParameter("ActualizarTrabajosRealizados", actualizarTrabajosRealizados) :
                new ObjectParameter("ActualizarTrabajosRealizados", typeof(bool));
    
            var trabajosRealizadosParameter = trabajosRealizados != null ?
                new ObjectParameter("TrabajosRealizados", trabajosRealizados) :
                new ObjectParameter("TrabajosRealizados", typeof(string));
    
            var actualizarCordenadasCab24Parameter = actualizarCordenadasCab24.HasValue ?
                new ObjectParameter("ActualizarCordenadasCab24", actualizarCordenadasCab24) :
                new ObjectParameter("ActualizarCordenadasCab24", typeof(bool));
    
            var cordenadasCab24Parameter = cordenadasCab24 != null ?
                new ObjectParameter("CordenadasCab24", cordenadasCab24) :
                new ObjectParameter("CordenadasCab24", typeof(string));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            var idFormatoParameter = idFormato.HasValue ?
                new ObjectParameter("IdFormato", idFormato) :
                new ObjectParameter("IdFormato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarFolio", idFolioParameter, folioParameter, ciudadParameter, estadoParameter, clusterParameter, oLTParameter, clientesAfectadosParameter, fallaReportadaParameter, fechaYHoraDeAsignacionDespachoParameter, fechaYHoraDeAsignacionProvistaParameter, horaDeLlegadaALaZonaParameter, horaDeLaPrimeraMedicionParameter, ubicacionDePrimerSegundoNivelYDerivacionConSusFibrasParameter, causaDelDanoParameter, ubicacionDelDanoParameter, coordenadasDelDanoXParameter, coordenadasDelDanoYParameter, descripcionDeActividadesParameter, potencialIniciaParameter, potencialFinalParameter, fechaHoraFinalReparacionParameter, idPersona_TecnicoAtiendeParameter, idProveedorParameter, idPersona_SupervisorParameter, idPersona_AtendioDespachoParameter, justificacionDeSLAParameter, actualizarTrabajosRealizadosParameter, trabajosRealizadosParameter, actualizarCordenadasCab24Parameter, cordenadasCab24Parameter, idSesionParameter, idFormatoParameter);
        }
    
        public virtual int GuardarCargo(Nullable<int> idCargo, string cargo, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idCargoParameter = idCargo.HasValue ?
                new ObjectParameter("IdCargo", idCargo) :
                new ObjectParameter("IdCargo", typeof(int));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("Cargo", cargo) :
                new ObjectParameter("Cargo", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCargo", idCargoParameter, cargoParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual int GuardarCargoPersona(string idCargos, Nullable<int> idPersona, Nullable<long> idSesion)
        {
            var idCargosParameter = idCargos != null ?
                new ObjectParameter("IdCargos", idCargos) :
                new ObjectParameter("IdCargos", typeof(string));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarCargoPersona", idCargosParameter, idPersonaParameter, idSesionParameter);
        }
    
        public virtual int GuardarPersona(Nullable<int> idPersona, string nombre, string paterno, string materno, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarPersona", idPersonaParameter, nombreParameter, paternoParameter, maternoParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual int GuardarProveedor(Nullable<int> idProveedor, string proveedor, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(int));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("Proveedor", proveedor) :
                new ObjectParameter("Proveedor", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarProveedor", idProveedorParameter, proveedorParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual int GuardarServicio(Nullable<int> idServicio, string clave, string descripcion, Nullable<int> idUnidad, Nullable<decimal> precioUnitario, Nullable<int> idEstatus, Nullable<long> idSesion, Nullable<int> idClasificacionServicio, string materialNSC)
        {
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("IdServicio", idServicio) :
                new ObjectParameter("IdServicio", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("IdUnidad", idUnidad) :
                new ObjectParameter("IdUnidad", typeof(int));
    
            var precioUnitarioParameter = precioUnitario.HasValue ?
                new ObjectParameter("PrecioUnitario", precioUnitario) :
                new ObjectParameter("PrecioUnitario", typeof(decimal));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            var idClasificacionServicioParameter = idClasificacionServicio.HasValue ?
                new ObjectParameter("IdClasificacionServicio", idClasificacionServicio) :
                new ObjectParameter("IdClasificacionServicio", typeof(int));
    
            var materialNSCParameter = materialNSC != null ?
                new ObjectParameter("MaterialNSC", materialNSC) :
                new ObjectParameter("MaterialNSC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarServicio", idServicioParameter, claveParameter, descripcionParameter, idUnidadParameter, precioUnitarioParameter, idEstatusParameter, idSesionParameter, idClasificacionServicioParameter, materialNSCParameter);
        }
    
        public virtual int GuardarUnidad(Nullable<int> idUnidad, string unidad, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("IdUnidad", idUnidad) :
                new ObjectParameter("IdUnidad", typeof(int));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("Unidad", unidad) :
                new ObjectParameter("Unidad", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarUnidad", idUnidadParameter, unidadParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual ObjectResult<DatosFolio_Result> DatosFolio(Nullable<int> idFolio)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DatosFolio_Result>("DatosFolio", idFolioParameter);
        }
    
        public virtual int EliminarArchivo(Nullable<int> idArchivo, Nullable<long> idSesion)
        {
            var idArchivoParameter = idArchivo.HasValue ?
                new ObjectParameter("IdArchivo", idArchivo) :
                new ObjectParameter("IdArchivo", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarArchivo", idArchivoParameter, idSesionParameter);
        }
    
        public virtual int GuardarArchivo(Nullable<int> idFolio, Nullable<int> idTipoArchivo, Nullable<int> idCarpeta, string nombre, string extension, Nullable<long> idSesion, Nullable<int> orden, Nullable<int> evento)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            var idTipoArchivoParameter = idTipoArchivo.HasValue ?
                new ObjectParameter("IdTipoArchivo", idTipoArchivo) :
                new ObjectParameter("IdTipoArchivo", typeof(int));
    
            var idCarpetaParameter = idCarpeta.HasValue ?
                new ObjectParameter("IdCarpeta", idCarpeta) :
                new ObjectParameter("IdCarpeta", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("Orden", orden) :
                new ObjectParameter("Orden", typeof(int));
    
            var eventoParameter = evento.HasValue ?
                new ObjectParameter("Evento", evento) :
                new ObjectParameter("Evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarArchivo", idFolioParameter, idTipoArchivoParameter, idCarpetaParameter, nombreParameter, extensionParameter, idSesionParameter, ordenParameter, eventoParameter);
        }
    
        public virtual int GuardarClasificacionServicio(Nullable<int> idClasificacionServicio, string clasificacion, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idClasificacionServicioParameter = idClasificacionServicio.HasValue ?
                new ObjectParameter("IdClasificacionServicio", idClasificacionServicio) :
                new ObjectParameter("IdClasificacionServicio", typeof(int));
    
            var clasificacionParameter = clasificacion != null ?
                new ObjectParameter("Clasificacion", clasificacion) :
                new ObjectParameter("Clasificacion", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarClasificacionServicio", idClasificacionServicioParameter, clasificacionParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual int GuardarDepartamento(Nullable<int> idDepartamento, string departamento, string nombreGerente, string correo, string telefono, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idDepartamentoParameter = idDepartamento.HasValue ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(int));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var nombreGerenteParameter = nombreGerente != null ?
                new ObjectParameter("NombreGerente", nombreGerente) :
                new ObjectParameter("NombreGerente", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarDepartamento", idDepartamentoParameter, departamentoParameter, nombreGerenteParameter, correoParameter, telefonoParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual int GuardarDepartamentoFolio(Nullable<int> idFolio, Nullable<int> idDepartamento, Nullable<long> idSesion)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            var idDepartamentoParameter = idDepartamento.HasValue ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarDepartamentoFolio", idFolioParameter, idDepartamentoParameter, idSesionParameter);
        }
    
        public virtual int GuardarTrabajoRealizado(Nullable<int> idFolio, Nullable<int> idServicio, Nullable<int> cantidad, Nullable<int> idUnidad, Nullable<decimal> pu, string descripcion, Nullable<long> idSesion, Nullable<int> idTrabajoRealizado, Nullable<int> consecutivo)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("IdServicio", idServicio) :
                new ObjectParameter("IdServicio", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var idUnidadParameter = idUnidad.HasValue ?
                new ObjectParameter("IdUnidad", idUnidad) :
                new ObjectParameter("IdUnidad", typeof(int));
    
            var puParameter = pu.HasValue ?
                new ObjectParameter("Pu", pu) :
                new ObjectParameter("Pu", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            var idTrabajoRealizadoParameter = idTrabajoRealizado.HasValue ?
                new ObjectParameter("IdTrabajoRealizado", idTrabajoRealizado) :
                new ObjectParameter("IdTrabajoRealizado", typeof(int));
    
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarTrabajoRealizado", idFolioParameter, idServicioParameter, cantidadParameter, idUnidadParameter, puParameter, descripcionParameter, idSesionParameter, idTrabajoRealizadoParameter, consecutivoParameter);
        }
    
        public virtual int EliminarTrabajo(Nullable<int> idTrabajo, Nullable<long> idSesion)
        {
            var idTrabajoParameter = idTrabajo.HasValue ?
                new ObjectParameter("IdTrabajo", idTrabajo) :
                new ObjectParameter("IdTrabajo", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarTrabajo", idTrabajoParameter, idSesionParameter);
        }
    
        public virtual int ArchivosFotograficosPorFolio(Nullable<int> idFolio)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ArchivosFotograficosPorFolio", idFolioParameter);
        }
    
        public virtual ObjectResult<ArchivosPorFolio_Result> ArchivosPorFolio(Nullable<int> idFolio, Nullable<int> idCarpeta)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            var idCarpetaParameter = idCarpeta.HasValue ?
                new ObjectParameter("IdCarpeta", idCarpeta) :
                new ObjectParameter("IdCarpeta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ArchivosPorFolio_Result>("ArchivosPorFolio", idFolioParameter, idCarpetaParameter);
        }
    
        public virtual ObjectResult<CatalogoServicios_Result> CatalogoServicios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoServicios_Result>("CatalogoServicios");
        }
    
        public virtual int EliminarServicioPorFormato(Nullable<int> idServicio, Nullable<int> idFormato, Nullable<long> idSesion)
        {
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("IdServicio", idServicio) :
                new ObjectParameter("IdServicio", typeof(int));
    
            var idFormatoParameter = idFormato.HasValue ?
                new ObjectParameter("IdFormato", idFormato) :
                new ObjectParameter("IdFormato", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarServicioPorFormato", idServicioParameter, idFormatoParameter, idSesionParameter);
        }
    
        public virtual int GuardarFormato(Nullable<int> idFormato, string formato, Nullable<int> idEstatus, Nullable<long> idSesion)
        {
            var idFormatoParameter = idFormato.HasValue ?
                new ObjectParameter("IdFormato", idFormato) :
                new ObjectParameter("IdFormato", typeof(int));
    
            var formatoParameter = formato != null ?
                new ObjectParameter("Formato", formato) :
                new ObjectParameter("Formato", typeof(string));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarFormato", idFormatoParameter, formatoParameter, idEstatusParameter, idSesionParameter);
        }
    
        public virtual int GuardarServicioPorFormato(Nullable<int> idFormato, Nullable<int> idServicio, Nullable<long> idSesion)
        {
            var idFormatoParameter = idFormato.HasValue ?
                new ObjectParameter("IdFormato", idFormato) :
                new ObjectParameter("IdFormato", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("IdServicio", idServicio) :
                new ObjectParameter("IdServicio", typeof(int));
    
            var idSesionParameter = idSesion.HasValue ?
                new ObjectParameter("IdSesion", idSesion) :
                new ObjectParameter("IdSesion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarServicioPorFormato", idFormatoParameter, idServicioParameter, idSesionParameter);
        }
    
        public virtual ObjectResult<ServiciosPorFolio_Result> ServiciosPorFolio(Nullable<int> idFolio)
        {
            var idFolioParameter = idFolio.HasValue ?
                new ObjectParameter("IdFolio", idFolio) :
                new ObjectParameter("IdFolio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServiciosPorFolio_Result>("ServiciosPorFolio", idFolioParameter);
        }
    }
}
