//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        public int IdModulo { get; set; }
        public string Modulo { get; set; }
        public int IdCabecera { get; set; }
        public string Icono { get; set; }
        public string Url { get; set; }
    }
}
