//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwArchivos
    {
        public int IdArchivo { get; set; }
        public int IdFolio { get; set; }
        public int IdTipoArchivo { get; set; }
        public int IdCarpeta { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public long IdSesion { get; set; }
        public string TipoArchivo { get; set; }
        public string RutaCarpeta { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Evento { get; set; }
    }
}
